pipeline {
  agent {
    docker { image 'python:latest' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'python --version'
        sh '''
          echo 'print("hello world")' > hello.py
          python hello.py
        '''
      }
      
    }
  }
}
