pipeline {
    agent any
    stages {
        stage('print hello world') {
            steps {
                sh 'echo "hello world"'
            }
        }
        stage('print python version') {
            steps {
                sh 'python --version'
            }
        }
    }
}
  
  
